name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"
  push: # 添加这个触发条件，指定当推送事件发生时执行工作流
    branches:
      - main # 可以指定特定分支或通配符，如 '*' 表示所有分支

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: torres7707
          author_email: wangdong7707@gmail.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
