name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: "Set node"
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Remove old pictures"
        run: rm -rf pictures/*

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        uses: EndBug/add-and-commit@v9
        with:
          author_name: torres7707
          author_email: wangdong7707@gmail.com
          message: "feat: save robot"
          add: "pictures/*"
          push: true
          token: ${{ github.token }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
