name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Remove files"
        run: |
          git config --local user.email "wangdong7707@gmail.com"
          git config --local user.name "torres7707"
          git pull origin main
          rm -f pictures/*.png
          git add -A

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: torres7707
          author_email: wangdong7707@gmail.com
          message: "feat: update robot"
          add: "pictures/*.png"
          remove: "pictures/*.png"
          pull: "--rebase"
          force: false

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
